### ISSUE TITLE
Add update agent example application

### ISSUE THREAD

**Issue by k-gostev** [eclipse-kanto/example-applications#4]
An update agent example application should be added. The agent has to implement the APIs defined [here](https://github.com/eclipse-kanto/update-manager/blob/main/docs/update-agent-api.md).
The update agent should have the ability to be run as a standalone app, similar to the other Kanto components, and also it should have a 'Dockerfile' similar to the [vehicle-simulator](https://github.com/eclipse-kanto/example-applications/blob/main/vehicle-simulator/Dockerfile). What the update agent will actually do is subject to the author creativity and/or could be discussed in the comments here.

**Comment by GabrielaY** [comment]
I can take this task.

**Comment by gabriela-yoncheva** [comment]
I can take this task.
