### ISSUE TITLE
Missing flags in deployment file of vehicle-simulator

### ISSUE THREAD

**Issue by IvanBoychevMarinov** [eclipse-kanto/example-applications#9]
While experimenting with containerized version of vehicle simulator I noticed the container was not starting properly. The reason was that the app was trying to connect to localhost:1883 although there is additional host declared - ctrhost. 
To make it run I had to add "--broker-url=tcp://ctrhost:1883"  in the "cmd" json array.

Perhaps it makes sense to add all available flags, even with empty values to make it clear what can be used.

**Comment by kv2143** [comment]
Hi Ivan,
Will check on this.
